name: Create repository using GitHub Actions plugin

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: "What is the name of your repository that you want to create?"
        required: true
        default: 'NewRepo'

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CUSTOM_TOKEN }}
          script: |
            github.rest.repos.createInOrg({
              org: context.repo.owner,
              name: ${{ github.event.inputs.repo-name }}
            })
